### PR TITLE
Refactor createCardHtml again so it's reusable

### PR DESCRIPTION
**Pull request by tialaaa**
## Describe your changes:
[//]: <> (Which files were changed? What changes were made?)
Final (hopefully) refactor of the createCardHtml function. By changing the function createCardHtml's parameter to be an _individualCard_ (instead of an array) and adjusting where/when the For loop happens, this update makes it reusable within the search bar's filterText function - accomplishing our goal of being more DRY with all uses of the innerHTML.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have tested the functionality of any new or updated features in the browser, if applicable
- [x] I have added one or more people as "Reviewers" to review & merge

### CODE REVIEW

**Comment by sdtrachsel** [comment]
Plan on reviewing the changes on Monday? I’m kind of iffy on all the repeated code that was needed to  change the function  from taking an array to only taking one card object.  The new page state global variable is  repeat of the show button class list. If we move the reference into the find text function, we can remove all the add ons to maintain that variable.

After seeing your code, I think we can revert back to function taking an array, create a function that generates the favorite array and drop it in the showStarred and text search.

**Comment by tialaaa** [comment]
Yes let's definitely review. We were running into issues using the createCardHTML function within the filterText function when it was using an array as the argument. The For loop within createCardHtml was causing it to push the whole array during the filter process, essentially removing the filter functionality.

**Review by CodeMeister362 — APPROVED** [review]
Code looks good and will add the needed search bar functionality of live searching while typing into the search as well as taking away the displayed cards depending on the text in the search bar.

**Comment by Adam-Meza** [comment]
All the changes to the CreateCard() look good! Good call on changing the parameter names and making it more dynamic.

**Pull request merged**
